version: "3"
services:
  rabbitmq:
    hostname: mq
    domainname: dv1.tenna.com
    container_name: mq
    image: tenna/rabbitmq:latest
    restart: always

  mongodb:
    hostname: mongo
    domainname: dv1.tenna.com
    container_name: mongo
    image: tenna/mongodb:latest
    restart: always
    
  tenna-ui:
    hostname: tenna-ui
    domainname: dv1.tenna.com
    container_name: tenna-ui
    image: tenna-ui:0.5.0
    restart: always
    ports:
      - "9080:8081"
    
  redis:
    image: tenna/redis:latest
    hostname: redis40
    domainname: dv1.tenna.com
    container_name: redisten40

  postgres:
    hostname: tennadb40
    domainname: dv1.tenna.com
    image: tenna/postgresql:latest
    container_name: tennadb40
    ports:
      - "9432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_development

  backend-web:
    image: backend-web:0.5.0
    container_name: backend-web
    volumes:
      - backend-web-opt:/opt/tenna-crud
    ports:
      - "9003:3000"
    links:
      - "postgres"
      - "redis"
    environment:
      NODE_ENV: development

volumes:
  backend-web-opt: